"""Hybrid deterministic/stochastic solver for the coupled cell.

Operator-split lockstep:
  - Metabolism: deterministic ODE (LSODA), state in mM, smooth
  - Gene network: tau-leaping stochastic (Cao et al.-style),
    state in molecule counts, captures intrinsic noise
  - Coupling: at each macro step delta_t,
      1. Advance metabolism by delta_t with current state.
         (One-way coupling: gene state never feeds back into metabolism.)
      2. Compute f_met from end-of-step metabolism state.
      3. Advance gene network by delta_t with synthesis propensities
         scaled by f_met (held constant over the macro step).

This is the simplest correct splitting for one-way coupling and matches
the Strang-symmetric scheme degenerated by the absence of back-coupling.
For two-way coupling we would need to symmetrize (1/2 met -> gene -> 1/2 met).

Why hybrid and not just stochastic-everything? Chassagnole's metabolites
are at 1e3-1e6 molecules per cell -- shot noise is negligible and the
ODE is ~3-4 orders of magnitude cheaper than SSA on the same system.
The Vilar gene network has DA=DR=1, mRNA often below 1 on average; this
is exactly where deterministic ODEs lie. Vilar 2002's central claim
(noise-resistance) cannot be tested at all without the stochastic path.

RNG hygiene: a single ``np.random.Generator`` is created from ``seed``
(or accepted explicitly via ``rng=``) and threaded through the full
realisation. No global state mutated; parallel realisations are safe.
See ``.github/copilot-instructions.md`` "Stochastic RNG discipline".
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.integrate import solve_ivp

from opencell.models.coupled import (
    PTS_REACTION_INDEX,
    SECONDS_PER_HOUR,
    SYNTHESIS_REACTION_INDICES,
    CoupledMetabolismTranscription,
)


@dataclass
class HybridResult:
    """Trajectory from a hybrid run.

    All times in seconds. ``ts`` are the macro-step boundaries (saved
    after each gene tau-leap segment). ``y_met`` and ``y_gene`` are
    sampled at the same boundaries.
    """

    ts: np.ndarray
    y_met: np.ndarray
    y_gene: np.ndarray
    f_met_history: np.ndarray
    n_tau_steps: int


def _gene_propensity_factory(coupled: CoupledMetabolismTranscription, f_met_value: float):
    """Build a propensity function for the gene network at a fixed f_met.

    Vilar's SBML kineticLaws are in **hour^-1** (the SBML's native time unit).
    The hybrid solver runs in **seconds** to share a clock with metabolism,
    so we convert per-hour propensities to per-second by dividing by 3600.
    Synthesis fluxes are then scaled by f_met; all other fluxes pass through.
    """
    gene = coupled.gene
    synth_set = set(SYNTHESIS_REACTION_INDICES)
    n_r = gene.n_reactions
    inv_seconds_per_hour = 1.0 / SECONDS_PER_HOUR

    def propensity(y_arr):
        y_np = np.asarray(y_arr, dtype=np.float64)
        v_per_h = gene.fluxes(0.0, y_np)
        v_per_s = v_per_h * inv_seconds_per_hour
        scaled = v_per_s.copy()
        for j in range(n_r):
            if j in synth_set:
                scaled[j] = scaled[j] * f_met_value
        scaled = np.maximum(scaled, 0.0)
        return scaled  # np.ndarray; tau_leap converts internally

    return propensity


def hybrid_run(
    coupled: CoupledMetabolismTranscription,
    t_end_s: float,
    macro_dt_s: float,
    seed: int = 0,
    epsilon: float = 0.03,
    tau_dt_max: float | None = None,
    met_atol: float = 1e-9,
    met_rtol: float = 1e-6,
    y0_override: np.ndarray | None = None,
    rng: np.random.Generator | None = None,
) -> HybridResult:
    """Run one realisation of the hybrid coupled simulator.

    Args:
        coupled: composite model (signal field selects f_met source)
        t_end_s: total cellular time in seconds
        macro_dt_s: lockstep macro step (seconds). Should be small enough
            that f_met is approximately constant within the step.
        seed: PRNG seed (used iff ``rng`` is None).
        epsilon: tau-leap epsilon
        tau_dt_max: max single tau-leap step; defaults to macro_dt_s
        met_atol, met_rtol: LSODA tolerances for the metabolism block
        y0_override: optional initial state (n_met + n_gene)
        rng: optional explicit ``np.random.Generator``. If provided,
            ``seed`` is ignored. Use this for ensembles to keep each
            realisation independent without touching numpy global state.
    """
    from opencell.solvers.stochastic import TauLeapConfig, tau_leap

    if tau_dt_max is None:
        tau_dt_max = macro_dt_s

    y0 = coupled.initial_y if y0_override is None else np.asarray(y0_override, dtype=np.float64)
    n_met = coupled.n_met
    y_met0 = y0[:n_met].copy()
    y_gene = y0[n_met:].copy()
    gene_stoich = coupled.gene.sbml.stoich

    if rng is None:
        rng = np.random.default_rng(seed)
    config = TauLeapConfig(epsilon=epsilon, dt_max=tau_dt_max)

    # Macro-step boundaries (seconds). Last bin may be shorter.
    n_macro = int(np.ceil(t_end_s / macro_dt_s))
    ts = np.array([min(i * macro_dt_s, t_end_s) for i in range(n_macro + 1)])

    # One-way coupling: metabolism does not depend on gene state or f_met,
    # so solve it once over the full horizon and sample at macro boundaries.
    # This avoids restarting LSODA n_macro times (~75% speedup vs per-step).
    sol = solve_ivp(
        coupled.met.rhs, (0.0, t_end_s), y_met0,
        method="LSODA", atol=met_atol, rtol=met_rtol, t_eval=ts,
    )
    if not sol.success:
        raise RuntimeError(f"metabolism LSODA failed: {sol.message}")
    y_met_traj = sol.y.T  # shape (n_macro+1, n_met)

    y_gene_hist = [y_gene.copy()]
    f_met_hist = [_compute_f_met(coupled, ts[0], y_met_traj[0])]
    total_tau_steps = 0

    for i in range(n_macro):
        dt = ts[i + 1] - ts[i]
        if dt <= 0:
            y_gene_hist.append(y_gene.copy())
            f_met_hist.append(f_met_hist[-1])
            continue

        # f_met from end-of-segment metabolism state (held constant for the gene segment).
        f = _compute_f_met(coupled, ts[i + 1], y_met_traj[i + 1])

        prop_fn = _gene_propensity_factory(coupled, f)
        seg = tau_leap(
            propensity_fn=prop_fn,
            stoich_matrix=gene_stoich,
            y0=y_gene,
            t_span=(0.0, dt),
            rng=rng,
            config=config,
            save_every=10**9,
        )
        y_gene = seg.ys[-1].copy()
        total_tau_steps += seg.n_steps

        y_gene_hist.append(y_gene.copy())
        f_met_hist.append(f)

    return HybridResult(
        ts=ts,
        y_met=y_met_traj,
        y_gene=np.array(y_gene_hist),
        f_met_history=np.array(f_met_hist),
        n_tau_steps=total_tau_steps,
    )


def _compute_f_met(coupled: CoupledMetabolismTranscription, t_s: float, y_met: np.ndarray) -> float:
    if coupled.signal == "uptake_flux":
        v_pts = float(coupled.met.sbml.fluxes(t_s, y_met)[PTS_REACTION_INDEX])
        return coupled.f_met_fn(v_pts, coupled.v_pts_init)
    return coupled.f_met_fn(float(y_met[coupled.cglcex_index]), coupled.cglcex_init)


def hybrid_ensemble(
    coupled: CoupledMetabolismTranscription,
    t_end_s: float,
    macro_dt_s: float,
    n_realisations: int,
    base_seed: int = 0,
    **kwargs,
) -> list[HybridResult]:
    """Convenience: run ``n_realisations`` independent realisations.

    Each realisation gets its own ``np.random.Generator`` derived from
    ``np.random.SeedSequence(base_seed).spawn(n_realisations)`` -- the
    canonical safe way to make independent streams from a single seed.
    """
    seq = np.random.SeedSequence(base_seed)
    children = seq.spawn(n_realisations)
    return [
        hybrid_run(coupled, t_end_s, macro_dt_s,
                   rng=np.random.default_rng(child), **kwargs)
        for child in children
    ]
