% Driver: runs buildProteinComplexs_montecarlokinetic for seeds 0..49
% against the pre-registered network-2-competition perturbed state,
% writing one CSV row per seed (built complex counts) to the gitignored
% raw-output directory. Reads the perturbed pool/stoichiometry from
% macromol_network2_state.m (generated by
% scripts/l22_evidence/h12_perturbation.py generate-inputs).
run(fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'm1_sources', ...
    'karr_native', 'h12_perturbation_traces', 'macromol_network2_state.m'));

n_seeds = 50;
n_complexes = size(block, 2);
out = zeros(n_seeds, n_complexes);

for seed = 0:(n_seeds - 1)
    rand('seed', seed);
    rs.rand = @() rand();
    built = buildProteinComplexs_montecarlokinetic(pool, block, rs);
    out(seed + 1, :) = built';
end

out_dir = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'm1_sources', ...
    'karr_native', 'h12_perturbation_traces');
csvwrite(fullfile(out_dir, 'macromol_network2_after.csv'), out);
printf('wrote %d seeds x %d columns to macromol_network2_after.csv\n', n_seeds, n_complexes);
