% Driver: runs evolveState_ppii for the pre-registered Scenario B scarcity-
% matrix states (see PERTURBATION_SPEC.json
% protein_processing_ii_scenario_b_scarcity_matrix), writing one CSV per
% state to the gitignored raw-output directory. Reads each state's
% perturbed initial condition from ppii_scenario_b_<name>_state.m
% (generated by scripts/l22_evidence/h12_perturbation.py
% generate-inputs-scenario-b -- tracked generator, gitignored generated
% data files).
%
% Mode is selected via the PPII_SCENARIO_B_MODE environment variable:
%   'canary' -> water_scarce state only, seeds 0-4 (5 total)
%   'full'   -> all 5 states, seeds 0-49 each (250 total)
%   (unset)  -> defaults to 'full'
%
% evolveState_ppii.m (the verbatim vendored ProteinProcessingII.m
% evolveState transcription, lines 349-445) is reused UNCHANGED from
% Scenario A -- this driver introduces no new source transcription, only
% a new pre-registered set of initial states and a loop over them.
%
% NOT INVOKED by anything in this commit -- Octave execution requires
% explicit follow-up authorization (canary: after Opus5 review of this
% code/spec commit; full: after GPT-5.6 Sol authorization following
% canary review). See PERTURBATION_SPEC.json scenario_b_execution_status.
state_dir = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'm1_sources', ...
    'karr_native', 'h12_perturbation_traces');

mode = getenv('PPII_SCENARIO_B_MODE');
if isempty(mode)
    mode = 'full';
end

all_state_names = {'water_scarce', 'pg160_scarce', 'peptidase_capacity_scarce', ...
    'transferase_capacity_scarce', 'simultaneous_peptidase_capacity_and_water_scarce'};

if strcmp(mode, 'canary')
    state_names = {'water_scarce'};
    n_seeds = 5;
elseif strcmp(mode, 'full')
    state_names = all_state_names;
    n_seeds = 50;
else
    error('run_ppii_scenario_b:badMode', 'PPII_SCENARIO_B_MODE must be ''canary'' or ''full'', got ''%s''', mode);
end

for i = 1:numel(state_names)
    name = state_names{i};
    % Each state's `this0` is loaded fresh from its own generated .m file
    % (independent pre-registered initial condition per state).
    run(fullfile(state_dir, ['ppii_scenario_b_', name, '_state.m']));
    n_mono = numel(this0.unprocessedMonomers);
    n_sub = numel(this0.substrates);
    out = zeros(n_seeds, 3 * n_mono + n_sub);

    for seed = 0:(n_seeds - 1)
        % Independent reseed per (state, seed) pair -- never a shared/
        % ambient RNG stream, never reused across states.
        rand('seed', seed);
        this = this0;
        this = evolveState_ppii(this);
        row = [this.unprocessedMonomers', this.processedMonomers', this.signalSequenceMonomers', this.substrates'];
        out(seed + 1, :) = row;
    end

    csvwrite(fullfile(state_dir, ['ppii_scenario_b_', name, '_after.csv']), out);
    printf('wrote %d seeds x %d columns to ppii_scenario_b_%s_after.csv\n', n_seeds, size(out, 2), name);
end
