% Driver: runs evolveState_ppii for seeds 0..49 against the pre-registered
% Scenario A (full-saturating) perturbed state, writing one CSV row per
% seed to the gitignored raw-output directory. Reads the perturbed state
% from ppii_scenario_a_state.m (generated by
% scripts/l22_evidence/h12_perturbation.py generate-inputs -- tracked
% generator, gitignored generated data file).
run(fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'm1_sources', ...
    'karr_native', 'h12_perturbation_traces', 'ppii_scenario_a_state.m'));

n_seeds = 50;
n_mono = numel(this0.unprocessedMonomers);
n_sub = numel(this0.substrates);
out = zeros(n_seeds, 3 * n_mono + n_sub);

for seed = 0:(n_seeds - 1)
    rand('seed', seed);
    this = this0;
    this = evolveState_ppii(this);
    row = [this.unprocessedMonomers', this.processedMonomers', this.signalSequenceMonomers', this.substrates'];
    out(seed + 1, :) = row;
end

out_dir = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'm1_sources', ...
    'karr_native', 'h12_perturbation_traces');
csvwrite(fullfile(out_dir, 'ppii_scenario_a_after.csv'), out);
printf('wrote %d seeds x %d columns to ppii_scenario_a_after.csv\n', n_seeds, size(out, 2));
