% extract_per_process_traces_batch_a.m
% Processes 1-7 (Metabolism + DNA-related)

this_file = mfilename('fullpath');
matlab_dir = fileparts(this_file);
addpath(matlab_dir);

process_names = { ...
    'Metabolism', ...
    'ReplicationInitiation', ...
    'Replication', ...
    'DNADamage', ...
    'DNARepair', ...
    'DNASupercoiling', ...
    'ChromosomeCondensation' ...
};

extract_per_process_traces(process_names, 'per_process_traces', 100);
fprintf('\n[batch_a] DONE\n');
