% extract_host_interaction_active_window.m
%
% Genuine, source-faithful window extraction for HostInteraction's L2.1
% active-window closure. Two parts:
%
%  (1) POSITIVE control -- a plain FIXED window (replaces the abandoned
%      false->true anchor SEARCH: the empirical canary in
%      scripts/matlab/probe_host_interaction_canary.m proved
%      host.isBacteriumAdherent (and isTLRActivated/isNFkBActivated/
%      isInflammatoryResponseActivated) are ALREADY TRUE at tick 1 of a
%      genuine seed-0 run and remain true through tick 100 -- Karr's
%      fitted initial condition already carries nonzero copy numbers for
%      every required enzyme, so a false->true transition search can
%      never terminate; this is not a code bug, it is the correct, honest
%      negative result for that search strategy). window_contract='fixed',
%      tick_offset=0, n_ticks=100, seed=0, output_subdir
%      'per_process_traces_v2_event_s000'.
%
%  (2) DISCRIMINATING CONDITIONS -- a constant-True window is degenerate
%      evidence on its own (Opus review, 2026-09-05): it cannot
%      distinguish a literal boolean-cascade port from a hardcoded
%      `return True` stub. Extracts the 5 preregistered enzyme-knockout
%      conditions from
%      docs/phase_f/l2_1/HOSTINTERACTION_CONDITION_PREREGISTRATION.md
%      (NEG_ADHERENCE, PARTIAL_ADHERENT_NO_SIGNAL, TLR12_PATH, TLR26_PATH,
%      ANTIGEN_ONLY), each a genuine, source-legal INPUT-SIDE enzyme
%      override (extraction_opts.per_process_enzyme_overrides.HostInteraction,
%      applied to the process-local `this.enzymes` vector every tick --
%      never touching Karr's own `host` output booleans), n_ticks=5,
%      tick_offset=0, seed=0, window_contract='fixed',
%      capture_signal_container=true (same signal surface as the positive
%      control). Each condition writes to its own output_subdir so the 5
%      short traces never collide with each other or with the positive
%      control.
%
% All 6 traces (1 positive + 5 discriminating) are produced by this one
% script/one MATLAB session, satisfying "one compact multi-condition
% artifact" -- no additional seeds, no output injection, no fabricated
% signal anywhere.
repo_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
cd(repo_root);
addpath(fullfile(repo_root, 'scripts', 'matlab'));

% --- (1) Positive control (unperturbed fitted seed-0 state) -------------
extract_per_process_traces_v2( ...
    {'HostInteraction'}, ...
    'per_process_traces_v2_event_s000', ...
    100, ...
    uint32(0), ...
    0, ...
    'fixed', ...
    struct( ...
        'signal_kind', 'boolean_transition', ...
        'signal_property', 'host', ...
        'signal_field', 'isBacteriumAdherent', ...
        'capture_signal_container', true ...
    ), ...
    struct( ...
        'condition_label', 'host_conditioned_genuine_seed0_fixed_active_window' ...
    ) ...
);

% --- (2) Discriminating conditions (preregistered enzyme knockouts) -----
conditions = struct( ...
    'id', {}, 'overrides', {}, 'condition_label', {});

conditions(end + 1) = struct( ...
    'id', 'neg_adherence', ...
    'overrides', struct('MG_218_MONOMER', 0), ...
    'condition_label', 'host_condition_neg_adherence');

conditions(end + 1) = struct( ...
    'id', 'partial_adherent_no_signal', ...
    'overrides', struct( ...
        'MG_075_MONOMER', 0, ...
        'MG_149_MONOMER', 0, ...
        'MG_309_MONOMER', 0, ...
        'MG_412_MONOMER', 0, ...
        'MG_410_411_412_PENTAMER', 0), ...
    'condition_label', 'host_condition_partial_adherent_no_signal');

conditions(end + 1) = struct( ...
    'id', 'tlr12_path', ...
    'overrides', struct('MG_309_MONOMER', 0), ...
    'condition_label', 'host_condition_tlr12_path');

conditions(end + 1) = struct( ...
    'id', 'tlr26_path', ...
    'overrides', struct( ...
        'MG_149_MONOMER', 0, ...
        'MG_412_MONOMER', 0, ...
        'MG_410_411_412_PENTAMER', 0), ...
    'condition_label', 'host_condition_tlr26_path');

conditions(end + 1) = struct( ...
    'id', 'antigen_only', ...
    'overrides', struct( ...
        'MG_149_MONOMER', 0, ...
        'MG_309_MONOMER', 0, ...
        'MG_412_MONOMER', 0, ...
        'MG_410_411_412_PENTAMER', 0), ...
    'condition_label', 'host_condition_antigen_only');

for c = 1:numel(conditions)
    cond = conditions(c);
    output_subdir = sprintf('per_process_traces_v2_host_condition_%s_s000', cond.id);
    extract_per_process_traces_v2( ...
        {'HostInteraction'}, ...
        output_subdir, ...
        5, ...
        uint32(0), ...
        0, ...
        'fixed', ...
        struct( ...
            'signal_kind', 'boolean_transition', ...
            'signal_property', 'host', ...
            'signal_field', 'isBacteriumAdherent', ...
            'capture_signal_container', true ...
        ), ...
        struct( ...
            'condition_label', cond.condition_label, ...
            'per_process_enzyme_overrides', struct('HostInteraction', cond.overrides) ...
        ) ...
    );
end
