% extract_per_process_traces_batch_b.m
% Processes 8-14 (RNA-related)

this_file = mfilename('fullpath');
matlab_dir = fileparts(this_file);
addpath(matlab_dir);

process_names = { ...
    'ChromosomeSegregation', ...
    'Transcription', ...
    'TranscriptionalRegulation', ...
    'RNAProcessing', ...
    'RNAModification', ...
    'RNADecay', ...
    'tRNAAminoacylation' ...
};

extract_per_process_traces(process_names, 'per_process_traces', 100);
fprintf('\n[batch_b] DONE\n');
