% extract_per_process_traces_batch_d.m
% Processes 22-28 (Translocation, complexation, division, terminal organelle)

this_file = mfilename('fullpath');
matlab_dir = fileparts(this_file);
addpath(matlab_dir);

process_names = { ...
    'ProteinTranslocation', ...
    'MacromolecularComplexation', ...
    'RibosomeAssembly', ...
    'FtsZPolymerization', ...
    'Cytokinesis', ...
    'HostInteraction', ...
    'TerminalOrganelleAssembly' ...
};

extract_per_process_traces(process_names, 'per_process_traces', 100);
fprintf('\n[batch_d] DONE\n');
