% extract_per_process_traces_batch_c.m
% Processes 15-21 (Protein-pipeline)

this_file = mfilename('fullpath');
matlab_dir = fileparts(this_file);
addpath(matlab_dir);

process_names = { ...
    'Translation', ...
    'ProteinProcessingI', ...
    'ProteinProcessingII', ...
    'ProteinModification', ...
    'ProteinFolding', ...
    'ProteinActivation', ...
    'ProteinDecay' ...
};

extract_per_process_traces(process_names, 'per_process_traces', 100);
fprintf('\n[batch_c] DONE\n');
