function probe_repinit_candidate_universe_at_tick(target_tick_0based)
% probe_repinit_candidate_universe_at_tick  Standalone, current-main-safe
% rewrite (see probe_repinit_advance_to_tick.m/probe_repinit_setup.m
% docstrings) of the generalized candidate-universe/weight-parity probe,
% parametrized by tick, used to independently verify the
% `_second_copy_site_mask` fix's `doubleStrandedRegions`-run-intersection
% logic against real MATLAB at any tick (e.g. 13, or a later tick like 55
% where the second copy's own polymerization has progressed to multiple,
% non-adjacent double-stranded runs -- a non-degenerate, stricter test).
%
% Dumps the REAL, full, ordered ADP- and ATP-path candidate universes
% (`positionsStrands`/`bindingRates`/`avgBindingRate`, from
% `calculateDnaAADPBindingRates`/`calculateDnaAATPBindingRates`, both
% deterministic/no-RNG-consumption -- verified by direct source read of
% ReplicationInitiation.m) and the `_has_second_chromosome`-equivalent
% boundary inputs (`collapse(polymerizedRegions)` vs `2*sequenceLen`)
% BEFORE any randsample call, to stdout.

if nargin < 1 || isempty(target_tick_0based)
    target_tick_0based = 13;
end

n_ticks = double(target_tick_0based) + 1;
trigger_tick = n_ticks; % 1-based MATLAB tick == 0-based Python target tick

[sim, target_idx] = probe_repinit_setup('ReplicationInitiation', uint32(0));
[~, ~, result] = probe_repinit_advance_to_tick(sim, target_idx, trigger_tick, @local_candidate_universe_probe);

disp(result);
fprintf('[probe_repinit_candidate_universe_at_tick] done (tick=%d).\n', target_tick_0based);
end

function result = local_candidate_universe_probe(mod)
% local_candidate_universe_probe  Sibling (non-nested) local helper.
[polATPs, polADPs] = mod.calculateDnaAR1234Polymerization();
[positionsStrandsADP, bindingRatesADP, avgBindingRateADP] = mod.calculateDnaAADPBindingRates(polATPs, polADPs);
[positionsStrandsATP, bindingRatesATP, avgBindingRateATP] = mod.calculateDnaAATPBindingRates(polATPs, polADPs);

totalPolymerized = collapse(mod.chromosome.polymerizedRegions);
seqLen = mod.chromosome.sequenceLen;

numFreeDnaAADP = mod.enzymes(mod.enzymeIndexs_DnaA_1mer_ADP);
numFreeDnaAATP = mod.enzymes(mod.enzymeIndexs_DnaA_1mer_ATP);

[~, complexsADP] = find(mod.chromosome.complexBoundSites);
numFreeBindingSitesADP = numel(bindingRatesADP) ...
    - sum(complexsADP == mod.enzymeGlobalIndexs(mod.enzymeIndexs_DnaA_1mer_ATP)) ...
    - sum(complexsADP == mod.enzymeGlobalIndexs(mod.enzymeIndexs_DnaA_1mer_ADP));

result = struct( ...
    'positionsStrandsADP', double(positionsStrandsADP), ...
    'bindingRatesADP', double(bindingRatesADP(:)'), ...
    'avgBindingRateADP', double(avgBindingRateADP), ...
    'positionsStrandsATP', double(positionsStrandsATP), ...
    'bindingRatesATP', double(bindingRatesATP(:)'), ...
    'avgBindingRateATP', double(avgBindingRateATP), ...
    'n_candidates_ADP', double(size(positionsStrandsADP, 1)), ...
    'n_candidates_ATP', double(size(positionsStrandsATP, 1)), ...
    'nnz_bindingRatesADP', double(nnz(bindingRatesADP)), ...
    'nnz_bindingRatesATP', double(nnz(bindingRatesATP)), ...
    'totalPolymerized', double(totalPolymerized), ...
    'sequenceLen', double(seqLen), ...
    'twice_sequenceLen', double(2 * seqLen), ...
    'four_times_sequenceLen', double(4 * seqLen), ...
    'has_second_chromosome', totalPolymerized > 2 * seqLen, ...
    'numFreeDnaAADP', double(numFreeDnaAADP), ...
    'numFreeDnaAATP', double(numFreeDnaAATP), ...
    'numFreeBindingSitesADP', double(numFreeBindingSitesADP), ...
    'dnaABoxStartPositions', double(mod.dnaABoxStartPositions(:)') ...
);
end
