#!/usr/bin/env python3
"""Extract per-process schema TOMLs using fixture-first v2.1 rules."""

from __future__ import annotations

import argparse
import dataclasses
import re
from collections import OrderedDict
from pathlib import Path
from typing import Any

from scipy.io import loadmat


PROCESS_M_REL = Path(
    "data/m1_sources/WholeCell/src/+edu/+stanford/+covert/+cell/+sim/+process"
)
TRACE_DIR_REL = Path("data/m1_sources/karr_native/per_process_traces_v2")
TRACE_S000_DIR_REL = Path("data/m1_sources/karr_native/per_process_traces_v2_s000")
FIXTURE_DIR_REL = Path("data/karr_fixtures/per_process")
OUTPUT_DIR_REL = Path("data/schemas/per_process")

AUTOGEN_HEADER = (
    "# AUTOGENERATED by scripts/extract_per_process_schema_v2.py — DO NOT EDIT\n"
)

SCHEMA_VERSION = "2.1"
CANONICAL_POOLS = ("substrates", "enzymes", "monomers", "complexs", "rnas")


@dataclasses.dataclass(frozen=True)
class Paths:
    repo_root: Path
    process_dir: Path
    trace_dir: Path
    trace_s000_dir: Path
    fixture_dir: Path


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _existing_path(candidates: list[Path], label: str) -> Path:
    for candidate in candidates:
        if candidate.exists():
            return candidate
    tried = "\n".join(str(c) for c in candidates)
    raise FileNotFoundError(f"Unable to resolve {label}. Tried:\n{tried}")


def build_paths() -> Paths:
    repo_root = _repo_root()
    return Paths(
        repo_root=repo_root,
        process_dir=_existing_path(
            [repo_root / PROCESS_M_REL, Path("E:/opencell") / PROCESS_M_REL],
            "MATLAB process source directory",
        ),
        trace_dir=_existing_path(
            [repo_root / TRACE_DIR_REL, Path("E:/opencell") / TRACE_DIR_REL],
            "v2 trace directory",
        ),
        trace_s000_dir=_existing_path(
            [repo_root / TRACE_S000_DIR_REL, Path("E:/opencell") / TRACE_S000_DIR_REL],
            "v2_s000 trace directory",
        ),
        fixture_dir=_existing_path(
            [repo_root / FIXTURE_DIR_REL, Path("E:/opencell") / FIXTURE_DIR_REL],
            "fixture directory",
        ),
    )


def camel_to_snake(name: str) -> str:
    name = name.replace("tRNA", "TRNA")
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1)
    return s2.lower()


def _snake_to_process_name(snake_name: str) -> str:
    overrides = {
        "trna_aminoacylation": "tRNAAminoacylation",
        "fts_z_polymerization": "FtsZPolymerization",
        "dna_damage": "DNADamage",
        "dna_repair": "DNARepair",
        "dna_supercoiling": "DNASupercoiling",
        "rna_decay": "RNADecay",
        "rna_modification": "RNAModification",
        "rna_processing": "RNAProcessing",
    }
    if snake_name in overrides:
        return overrides[snake_name]
    return "".join(part.capitalize() for part in snake_name.split("_"))


def _to_str_list(raw: Any) -> list[str]:
    try:
        values = list(raw.ravel())  # numpy arrays
    except Exception:
        values = [raw]
    out: list[str] = []
    for item in values:
        obj = item
        while hasattr(obj, "shape") and getattr(obj, "shape", None) and getattr(obj, "size", 1) == 1:
            try:
                obj = obj.item()
            except Exception:
                break
        if isinstance(obj, bytes):
            text = obj.decode("utf-8", errors="replace").strip()
        else:
            text = str(obj).strip()
        if text:
            out.append(text)
    return out


def _dedupe_keep_order(values: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        out.append(value)
    return out


def _attr_to_pool(attr_name: str) -> str | None:
    lower = attr_name.lower()
    if "wholecellmodelid" not in lower:
        return None
    if "reaction" in lower or "stimuli" in lower or "stimulus" in lower:
        return None
    if "processwholecellmodelids" in lower:
        return None
    if "compartmentwholecellmodelids" in lower:
        return None
    if "transcriptionunitwholecellmodelids" in lower:
        return None
    if "substrate" in lower:
        return "substrates"
    if "enzyme" in lower:
        return "enzymes"
    if "monomer" in lower:
        return "monomers"
    if "complex" in lower:
        return "complexs"
    if "rna" in lower:
        return "rnas"
    return None


def _line_number(text: str, pattern: str) -> int:
    match = re.search(pattern, text, re.S)
    if not match:
        return -1
    return text[: match.start()].count("\n") + 1


def resolve_trace_file(process_name: str, paths: Paths) -> tuple[Path, str]:
    s000 = paths.trace_s000_dir / f"{process_name}_100ticks.mat"
    if s000.exists():
        return s000, "per_process_traces_v2_s000"
    fallback = paths.trace_dir / f"{process_name}_100ticks.mat"
    if fallback.exists():
        return fallback, "per_process_traces_v2"
    raise FileNotFoundError(f"Trace file missing for {process_name}")


def resolve_fixture_file(process_name: str, paths: Paths) -> Path:
    fixture_file = paths.fixture_dir / f"{process_name}_flat.mat"
    if fixture_file.exists():
        return fixture_file
    raise FileNotFoundError(f"Fixture file missing for {process_name}: {fixture_file}")


def list_process_names(paths: Paths) -> list[str]:
    names: list[str] = []
    for path in sorted(paths.process_dir.glob("*.m")):
        names.append(path.stem)
    return names


def extract_species_pools_from_fixture(fixture_file: Path) -> tuple[dict[str, list[str]], dict[str, int]]:
    mat = loadmat(str(fixture_file), squeeze_me=True, struct_as_record=False)
    data = mat.get("data")
    if data is None or not hasattr(data, "fixture"):
        raise ValueError("Fixture MAT missing data.fixture root")
    fixture = data.fixture

    pooled: dict[str, list[str]] = {pool: [] for pool in CANONICAL_POOLS}
    source_attrs = 0
    for attr_name in dir(fixture):
        pool = _attr_to_pool(attr_name)
        if pool is None:
            continue
        source_attrs += 1
        pooled[pool].extend(_to_str_list(getattr(fixture, attr_name)))
    deduped = {pool: _dedupe_keep_order(values) for pool, values in pooled.items()}
    counts = {pool: len(values) for pool, values in deduped.items()}
    counts["source_attrs"] = source_attrs
    return deduped, counts


def extract_process_schema(process_name: str, paths: Paths) -> dict[str, Any]:
    matlab_source = paths.process_dir / f"{process_name}.m"
    if not matlab_source.exists():
        raise FileNotFoundError(f"MATLAB source missing for {process_name}")
    trace_file, trace_source = resolve_trace_file(process_name, paths)
    fixture_file = resolve_fixture_file(process_name, paths)

    process_text = matlab_source.read_text(encoding="utf-8", errors="replace")
    species_pools, pool_counts = extract_species_pools_from_fixture(fixture_file)

    schema: dict[str, Any] = OrderedDict()
    schema["process"] = OrderedDict(
        [
            ("name", process_name),
            ("class", process_name),
            ("schema_version", SCHEMA_VERSION),
            (
                "matlab_source",
                str(
                    Path(
                        "data/m1_sources/WholeCell/src/+edu/+stanford/+covert/+cell/+sim/+process"
                    )
                    / f"{process_name}.m"
                ).replace("\\", "/"),
            ),
            (
                "trace_file",
                str(trace_file.relative_to(paths.repo_root)).replace("\\", "/"),
            ),
            (
                "fixture_file",
                str(fixture_file.relative_to(paths.repo_root)).replace("\\", "/"),
            ),
        ]
    )
    schema["species_pools"] = OrderedDict((pool, species_pools[pool]) for pool in CANONICAL_POOLS)
    schema["extractor_diagnostics"] = OrderedDict(
        [
            (
                "source_lines",
                OrderedDict(
                    [
                        ("classdef_line", _line_number(process_text, r"classdef\s+")),
                        (
                            "substrate_ids_line",
                            _line_number(process_text, r"substrateWholeCellModelIDs"),
                        ),
                        (
                            "enzyme_ids_line",
                            _line_number(process_text, r"enzymeWholeCellModelIDs"),
                        ),
                    ]
                ),
            ),
            (
                "provenance",
                OrderedDict(
                    [
                        ("wids_source", "fixture"),
                        ("trace_source", trace_source),
                        ("fixture_loader", "scipy.io.loadmat"),
                    ]
                ),
            ),
            ("species_pool_counts", pool_counts),
        ]
    )
    return schema


def _toml_escape_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _toml_scalar(value: Any) -> str:
    if isinstance(value, str):
        return f'"{_toml_escape_string(value)}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    raise TypeError(f"Unsupported scalar type: {type(value)!r}")


def _toml_value(value: Any) -> str:
    if isinstance(value, (str, bool, int)):
        return _toml_scalar(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    if isinstance(value, dict):
        items = ", ".join(f"{key} = {_toml_value(val)}" for key, val in value.items())
        return "{ " + items + " }"
    raise TypeError(f"Unsupported TOML type: {type(value)!r}")


def _emit_table(lines: list[str], table_name: str, table: dict[str, Any]) -> None:
    lines.append(f"[{table_name}]")
    for key, value in table.items():
        lines.append(f"{key} = {_toml_value(value)}")
    lines.append("")


def render_schema_toml(schema: dict[str, Any]) -> str:
    lines = [AUTOGEN_HEADER.rstrip("\n"), ""]
    _emit_table(lines, "process", schema["process"])
    _emit_table(lines, "species_pools", schema["species_pools"])
    _emit_table(lines, "extractor_diagnostics.source_lines", schema["extractor_diagnostics"]["source_lines"])
    _emit_table(lines, "extractor_diagnostics.provenance", schema["extractor_diagnostics"]["provenance"])
    _emit_table(
        lines,
        "extractor_diagnostics.species_pool_counts",
        schema["extractor_diagnostics"]["species_pool_counts"],
    )
    return "\n".join(lines).rstrip() + "\n"


def write_schema_file(process_name: str, schema: dict[str, Any], output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{camel_to_snake(process_name)}.toml"
    out_path.write_text(render_schema_toml(schema), encoding="utf-8")
    return out_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--process",
        action="append",
        default=[],
        help="Process name in CamelCase. Repeat for multiple.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(OUTPUT_DIR_REL),
        help="Output directory for generated TOMLs.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Resolve and parse inputs without writing output files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    paths = build_paths()
    output_dir = (
        Path(args.output_dir)
        if Path(args.output_dir).is_absolute()
        else paths.repo_root / args.output_dir
    )

    requested = args.process
    if requested:
        process_names = []
        for process in requested:
            if "_" in process:
                process_names.append(_snake_to_process_name(process))
            else:
                process_names.append(process)
    else:
        process_names = list_process_names(paths)

    written = 0
    for process_name in process_names:
        schema = extract_process_schema(process_name, paths)
        if args.dry_run:
            print(f"[dry-run] {process_name}: fixture/species_pools parsed")
            continue
        out = write_schema_file(process_name, schema, output_dir)
        written += 1
        print(f"[ok] {process_name} -> {out}")

    if not args.dry_run:
        print(f"wrote {written}/{len(process_names)} schema files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
