#!/usr/bin/env python3
"""Extract per-process schema TOMLs from MATLAB sources and trace MAT files.

This extractor is correctness-anchored to MATLAB process sources and per-process
trace files. It intentionally does not read OpenCell Python process sources.
"""

from __future__ import annotations

import argparse
import dataclasses
import re
from collections import OrderedDict
from pathlib import Path
from typing import Any, Iterable

import h5py
import numpy as np


PROCESS_M_REL = Path(
    "data/m1_sources/WholeCell/src/+edu/+stanford/+covert/+cell/+sim/+process"
)
COMPARTMENT_M_REL = Path(
    "data/m1_sources/WholeCell/src/+edu/+stanford/+covert/+cell/+sim/+constant/Compartment.m"
)
KNOWLEDGE_BASE_M_REL = Path(
    "data/m1_sources/WholeCell/src/+edu/+stanford/+covert/+cell/+kb/KnowledgeBase.m"
)
TRACE_DIR_REL = Path("data/m1_sources/karr_native/per_process_traces_v2")
FIXTURE_DIR_REL = Path("data/m1_sources/karr_native/per_process_fixtures_v2")
OUTPUT_DIR_REL = Path("data/schemas/per_process")

AUTOGEN_HEADER = (
    "# AUTOGENERATED by scripts/extract_per_process_schema.py — DO NOT EDIT\n"
)


@dataclasses.dataclass(frozen=True)
class Paths:
    repo_root: Path
    wholecell_root: Path
    trace_dir: Path
    fixture_dir: Path
    process_dir: Path
    compartment_m: Path
    knowledge_base_m: Path


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _resolve_wholecell_root(repo_root: Path, explicit: str | None) -> Path:
    candidates: list[Path] = []
    if explicit:
        candidates.append(Path(explicit))
    candidates.extend(
        [
            repo_root / "data/m1_sources/WholeCell",
            Path("E:/opencell/data/m1_sources/WholeCell"),
            Path("E:/opencell-mirrors/WholeCell"),
            Path("/mnt/e/opencell/data/m1_sources/WholeCell"),
            Path("/mnt/e/opencell-mirrors/WholeCell"),
        ]
    )
    for root in candidates:
        if (root / "src").exists():
            return root
    joined = "\n".join(str(p) for p in candidates)
    raise FileNotFoundError(
        "Unable to locate WholeCell MATLAB source root. Tried:\n" + joined
    )


def build_paths(wholecell_root: str | None = None) -> Paths:
    repo_root = _repo_root()
    wc_root = _resolve_wholecell_root(repo_root, wholecell_root)
    trace_dir_candidates = [
        repo_root / TRACE_DIR_REL,
        Path("E:/opencell") / TRACE_DIR_REL,
        Path("/mnt/e/opencell") / TRACE_DIR_REL,
    ]
    trace_dir = next((p for p in trace_dir_candidates if p.exists()), None)
    if trace_dir is None:
        tried = "\n".join(str(p) for p in trace_dir_candidates)
        raise FileNotFoundError(f"Unable to find trace directory. Tried:\n{tried}")

    fixture_dir_candidates = [
        repo_root / FIXTURE_DIR_REL,
        Path("E:/opencell") / FIXTURE_DIR_REL,
        Path("/mnt/e/opencell") / FIXTURE_DIR_REL,
    ]
    fixture_dir = next((p for p in fixture_dir_candidates if p.exists()), None)
    if fixture_dir is None:
        # Keep a canonical path handle even when missing.
        fixture_dir = repo_root / FIXTURE_DIR_REL

    return Paths(
        repo_root=repo_root,
        wholecell_root=wc_root,
        trace_dir=trace_dir,
        fixture_dir=fixture_dir,
        process_dir=wc_root / "src/+edu/+stanford/+covert/+cell/+sim/+process",
        compartment_m=wc_root / "src/+edu/+stanford/+covert/+cell/+sim/+constant/Compartment.m",
        knowledge_base_m=wc_root / "src/+edu/+stanford/+covert/+cell/+kb/KnowledgeBase.m",
    )


def camel_to_snake(name: str) -> str:
    # Preserve common biology acronyms.
    name = name.replace("tRNA", "TRNA")
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1)
    return s2.lower()


def _strip_comments(text: str) -> str:
    cleaned = []
    for line in text.splitlines():
        idx = line.find("%")
        if idx >= 0:
            line = line[:idx]
        cleaned.append(line)
    return "\n".join(cleaned)


def _balanced_span(text: str, start: int, open_ch: str, close_ch: str) -> tuple[int, int] | None:
    depth = 0
    in_str = False
    i = start
    while i < len(text):
        ch = text[i]
        if ch == "'":
            in_str = not in_str
            i += 1
            continue
        if in_str:
            i += 1
            continue
        if ch == open_ch:
            depth += 1
        elif ch == close_ch:
            depth -= 1
            if depth == 0:
                return (start, i + 1)
        i += 1
    return None


def _extract_assignment_blocks(text: str, symbol: str) -> list[tuple[str, str]]:
    """Return list[(lhs, rhs_block)] for symbol assignments."""
    out: list[tuple[str, str]] = []
    code = _strip_comments(text)
    lhs_re = re.compile(rf"(?P<lhs>(?:this\.)?{re.escape(symbol)}\w*)\s*=")
    for m in lhs_re.finditer(code):
        lhs = m.group("lhs")
        pos = m.end()
        while pos < len(code) and code[pos].isspace():
            pos += 1
        if pos >= len(code):
            continue

        if code.startswith("unique", pos):
            lbrace = code.find("{", pos)
            if lbrace != -1:
                span = _balanced_span(code, lbrace, "{", "}")
                if span:
                    out.append((lhs, code[span[0] : span[1]]))
            continue

        if code[pos] in "{[":
            open_ch = code[pos]
            close_ch = "}" if open_ch == "{" else "]"
            span = _balanced_span(code, pos, open_ch, close_ch)
            if span:
                out.append((lhs, code[span[0] : span[1]]))
            continue
    return out


def _extract_string_literals(block: str) -> list[str]:
    return [m.group(1) for m in re.finditer(r"'([^'\n\r]*)'", block)]


def extract_wids_from_matlab(text: str, symbol: str) -> tuple[list[str] | None, str]:
    blocks = _extract_assignment_blocks(text, symbol)
    if not blocks:
        return None, f"{symbol} assignment not found"

    values: list[str] = []
    saw_explicit_init = False
    partial_runtime_dependency = False

    for lhs, block in blocks:
        block_values = _extract_string_literals(block)
        if not block_values:
            continue
        has_self_ref = symbol in block and "this." + symbol in block
        if has_self_ref and not values:
            partial_runtime_dependency = True
            values.extend(block_values)
            continue
        if block.startswith("{") and not has_self_ref:
            if not saw_explicit_init:
                values = block_values
                saw_explicit_init = True
            else:
                values = block_values
        elif block.startswith("["):
            if has_self_ref:
                values.extend(block_values)
            else:
                values = block_values

    if not values:
        return None, f"{symbol} literals could not be parsed from MATLAB source"
    if partial_runtime_dependency and not saw_explicit_init:
        return (
            None,
            f"{symbol} depends on inherited/runtime state; literal append is partial",
        )
    return values, "ok"


def _extract_numeric_assignment(text: str, symbol: str) -> tuple[list[int] | None, str]:
    blocks = _extract_assignment_blocks(text, symbol)
    if not blocks:
        return None, f"{symbol} assignment not found"
    nums: list[int] = []
    for _, block in blocks:
        nums.extend(int(x) for x in re.findall(r"(?<![A-Za-z_])(-?\d+)(?![A-Za-z_])", block))
    if not nums:
        # Handle scalar numeric assignments without []/{}
        code = _strip_comments(text)
        scalar_pat = re.compile(
            rf"(?:this\.)?{re.escape(symbol)}\w*\s*=\s*(-?\d+)\s*;",
            re.S,
        )
        nums = [int(m.group(1)) for m in scalar_pat.finditer(code)]
    if not nums:
        return None, f"{symbol} found, but numeric literals were not parseable"
    return nums, "ok"


def _extract_numeric_named_assignments(text: str, symbol_prefix: str) -> OrderedDict[str, int]:
    code = _strip_comments(text)
    patt = re.compile(
        rf"(?P<lhs>(?:this\.)?{re.escape(symbol_prefix)}\w*)\s*=\s*(?P<num>-?\d+)\s*;",
        re.S,
    )
    out: OrderedDict[str, int] = OrderedDict()
    for m in patt.finditer(code):
        lhs = m.group("lhs")
        short = lhs.split(".")[-1]
        out[short] = int(m.group("num"))
    return out


def parse_classdef(text: str) -> tuple[str | None, str | None]:
    m = re.search(r"classdef\s+([A-Za-z0-9_]+)\s*<\s*([^\n%]+)", text)
    if not m:
        return None, None
    return m.group(1).strip(), m.group(2).strip()


def parse_compartment_wid_constants(knowledge_base_m_text: str) -> OrderedDict[str, str]:
    mapping: OrderedDict[str, str] = OrderedDict()
    patt = re.compile(
        r"(?P<name>\w+CompartmentWholeCellModelIDs)\s*=\s*\{(?P<body>[^}]*)\}",
        re.S,
    )
    for m in patt.finditer(knowledge_base_m_text):
        ids = _extract_string_literals("{" + m.group("body") + "}")
        if ids:
            mapping[m.group("name")] = ids[0]
    return mapping


def _decode_matlab_string_u16(arr: np.ndarray) -> str:
    flat = np.asarray(arr).reshape(-1)
    vals = [int(x) for x in flat if int(x) != 0]
    return "".join(chr(v) for v in vals)


def _tick_refs(dataset: h5py.Dataset) -> list[h5py.Reference]:
    if dataset.ndim != 2:
        return [dataset[idx] for idx in np.ndindex(dataset.shape)]
    if dataset.shape[0] == 1:
        return [dataset[0, i] for i in range(dataset.shape[1])]
    if dataset.shape[1] == 1:
        return [dataset[i, 0] for i in range(dataset.shape[0])]
    return [dataset[idx] for idx in np.ndindex(dataset.shape)]


def _load_tick_matrices(handle: h5py.File, group_name: str, observable: str) -> list[np.ndarray]:
    ds = handle[f"{group_name}/{observable}"]
    refs = _tick_refs(ds)
    out: list[np.ndarray] = []
    for ref in refs:
        out.append(np.asarray(handle[ref][()]))
    return out


def _infer_axes(shape: tuple[int, ...], wid_count: int | None) -> tuple[int, int, str]:
    if len(shape) != 2:
        return 0, 1, "fallback_non_2d"
    r, c = int(shape[0]), int(shape[1])
    if wid_count is not None:
        if r == wid_count and c != wid_count:
            return 0, 1, "wids_match_rows"
        if c == wid_count and r != wid_count:
            return 1, 0, "wids_match_cols"
        if r == wid_count and c == wid_count:
            return 0, 1, "ambiguous_square_wids_match_both_axes"
        return 0, 1, "wids_mismatch_shape_fallback_rows"
    return 0, 1, "wid_count_missing_fallback_rows"


def _infer_item_count_from_shape(shape: list[int] | None) -> int | dict[str, str]:
    if shape is None:
        return {"EXTRACTOR_FAILED": "shape missing"}
    if len(shape) == 2:
        r, c = int(shape[0]), int(shape[1])
        if r == 1 and c > 1:
            return c
        return r
    if len(shape) == 1:
        return int(shape[0])
    return {"EXTRACTOR_FAILED": f"unsupported shape rank: {shape}"}


def _observable_mutation_counts(trace_file: Path) -> tuple[dict[str, int], dict[str, list[int]]]:
    with h5py.File(trace_file, "r") as f:
        observables = sorted(set(f["states_before"].keys()) | set(f["states_after"].keys()))
        mutated: dict[str, int] = {}
        shapes: dict[str, list[int]] = {}
        for obs in observables:
            if f"states_before/{obs}" not in f or f"states_after/{obs}" not in f:
                mutated[obs] = 0
                continue
            before = _load_tick_matrices(f, "states_before", obs)
            after = _load_tick_matrices(f, "states_after", obs)
            n = min(len(before), len(after))
            if n > 0:
                shapes[obs] = [int(x) for x in before[0].shape]
            count = 0
            for i in range(n):
                if not np.array_equal(before[i], after[i]):
                    count += 1
            mutated[obs] = count
        return mutated, shapes


def _derive_trace_hint_keys(mutated: dict[str, int]) -> list[str]:
    out: list[str] = []
    for obs in ("boundEnzymes", "enzymes"):
        if mutated.get(obs, 0) > 0:
            out.append(f"{obs}_next")
    return out


def _derive_pass_through(mutated: dict[str, int]) -> list[str]:
    return sorted([k for k, v in mutated.items() if v == 0])


def _line_number(text: str, pattern: str) -> int | None:
    m = re.search(pattern, text, re.S)
    if not m:
        return None
    return text[: m.start()].count("\n") + 1


def _safe_field(value: Any, reason: str | None = None) -> Any:
    if reason:
        return {"EXTRACTOR_FAILED": reason}
    return value


def extract_process_schema(process_name: str, paths: Paths) -> dict[str, Any]:
    process_m = paths.process_dir / f"{process_name}.m"
    if not process_m.exists():
        raise FileNotFoundError(f"MATLAB process source not found: {process_m}")
    trace_file = paths.trace_dir / f"{process_name}_100ticks.mat"
    if not trace_file.exists():
        raise FileNotFoundError(f"Trace file not found: {trace_file}")
    fixture_file = paths.fixture_dir / f"{process_name}_fixture.mat"

    process_text = process_m.read_text(encoding="utf-8", errors="replace")
    kb_text = paths.knowledge_base_m.read_text(encoding="utf-8", errors="replace")

    class_name, class_base = parse_classdef(process_text)

    substrate_wids, substrate_reason = extract_wids_from_matlab(
        process_text, "substrateWholeCellModelIDs"
    )
    enzyme_wids, enzyme_reason = extract_wids_from_matlab(
        process_text, "enzymeWholeCellModelIDs"
    )
    substrate_compartments, substrate_comp_reason = _extract_numeric_assignment(
        process_text, "substrateCompartments"
    )
    local_compartment_indexes, local_compartment_reason = _extract_numeric_assignment(
        process_text, "compartmentIndexs"
    )
    local_compartment_named = _extract_numeric_named_assignments(
        process_text, "compartmentIndexs"
    )

    mutated, shapes = _observable_mutation_counts(trace_file)
    substrate_shape = shapes.get("substrates")
    enzymes_shape = shapes.get("enzymes")
    bound_shape = shapes.get("boundEnzymes")

    wid_count = len(substrate_wids) if substrate_wids is not None else None
    substrate_axis = 0
    compartment_axis = 1
    axis_method = "shape_missing"
    if substrate_shape is not None:
        substrate_axis, compartment_axis, axis_method = _infer_axes(
            tuple(substrate_shape), wid_count
        )

    compartment_dim = None
    if substrate_shape is not None and len(substrate_shape) >= 2:
        compartment_dim = int(substrate_shape[compartment_axis])

    compartments: Any
    compartments_method = "unresolved"
    compartments_notes = ""

    if substrate_compartments is not None:
        compartments = substrate_compartments
        compartments_method = "substrateCompartments"
        compartments_notes = "from MATLAB substrateCompartments numeric assignment"
    else:
        if substrate_shape is None:
            compartments = {"EXTRACTOR_FAILED": "substrates shape missing in trace"}
            compartments_method = "fallback"
            compartments_notes = "trace lacks substrates observable"
        elif compartment_dim is None:
            compartments = {
                "EXTRACTOR_FAILED": f"substrates observable is not 2D (shape={substrate_shape})"
            }
            compartments_method = "fallback"
            compartments_notes = "cannot infer compartment axis from non-2D substrate shape"
        else:
            active = np.zeros(compartment_dim, dtype=bool)
            with h5py.File(trace_file, "r") as f:
                before = _load_tick_matrices(f, "states_before", "substrates")
                after = _load_tick_matrices(f, "states_after", "substrates")
                for arr in before + after:
                    if arr.ndim != 2:
                        continue
                    if compartment_axis == 1:
                        active |= np.any(arr != 0, axis=0)
                    else:
                        active |= np.any(arr != 0, axis=1)

            active_idx = [i + 1 for i, v in enumerate(active.tolist()) if v]
            if not active_idx and local_compartment_indexes:
                active_idx = sorted(set(local_compartment_indexes))
            if not active_idx:
                active_idx = list(range(1, compartment_dim + 1))

            compartments = active_idx
            compartments_method = "trace_nonzero_scan"
            compartments_notes = (
                f"derived from substrates nonzero scan using axis_method={axis_method}"
            )

    kb_comp_map = parse_compartment_wid_constants(kb_text)
    kb_ordered_wids = list(kb_comp_map.values())
    compartment_wids: Any
    compartment_wids_notes = ""
    if isinstance(compartments, dict) and "EXTRACTOR_FAILED" in compartments:
        compartment_wids = {
            "EXTRACTOR_FAILED": "compartments unavailable, cannot map compartment_wids"
        }
    elif substrate_shape is None:
        compartment_wids = {"EXTRACTOR_FAILED": "substrates shape unavailable"}
    elif compartment_dim is None:
        compartment_wids = {
            "EXTRACTOR_FAILED": f"substrates shape {substrate_shape} is non-2D; no compartment axis"
        }
    else:
        if compartments_method == "substrateCompartments":
            mapped: list[str] = []
            for idx in compartments:
                if idx <= 0 or idx > len(kb_ordered_wids):
                    mapped.append(f"IDX_{idx}")
                else:
                    mapped.append(kb_ordered_wids[idx - 1])
            compartment_wids = mapped
            compartment_wids_notes = "mapped by index to KnowledgeBase compartment wid constants"
        elif local_compartment_named and len(set(local_compartment_named.values())) == compartment_dim:
            # Local compartment indexs can represent process-specific pseudo-compartments.
            # Preserve numeric slots as stable labels when direct wid mapping is not available.
            by_index = sorted((idx, name) for name, idx in local_compartment_named.items())
            labels: list[str] = []
            for idx, full_name in by_index:
                suffix = full_name.replace("compartmentIndexs_", "")
                labels.append(suffix if suffix != full_name else f"local_compartment_{idx}")
            compartment_wids = labels
            compartment_wids_notes = (
                "derived from process-local compartmentIndexs_* constants"
            )
        elif compartment_dim <= len(kb_ordered_wids):
            compartment_wids = kb_ordered_wids[:compartment_dim]
            compartment_wids_notes = (
                "fallback to leading KnowledgeBase compartment wid constants; verify manually"
            )
        else:
            compartment_wids = {
                "EXTRACTOR_FAILED": (
                    f"cannot map {compartment_dim} trace compartments to "
                    f"{len(kb_ordered_wids)} known KnowledgeBase wid constants"
                )
            }

    if substrate_wids is None:
        substrate_count_field = _safe_field(None, substrate_reason)
    else:
        substrate_count_field = len(substrate_wids)

    if enzyme_wids is None:
        enzyme_count_field = _safe_field(None, enzyme_reason)
    else:
        enzyme_count_field = len(enzyme_wids)

    bound_wids_field: Any
    if enzyme_wids is None:
        bound_wids_field = {"EXTRACTOR_FAILED": "enzyme wids unavailable"}
    else:
        bound_wids_field = list(enzyme_wids)

    mutation_profile: OrderedDict[str, Any] = OrderedDict()
    mutation_profile["bound_mutated_ticks"] = int(mutated.get("boundEnzymes", 0))
    mutation_profile["enzymes_mutated_ticks"] = int(mutated.get("enzymes", 0))
    mutation_profile["substrates_mutated_ticks"] = int(mutated.get("substrates", 0))
    mutation_profile["monomers_mutated_ticks"] = int(mutated.get("monomers", 0))
    mutation_profile["per_observable"] = OrderedDict(
        (k, int(v)) for k, v in sorted(mutated.items())
    )

    schema: dict[str, Any] = OrderedDict()
    schema["process"] = OrderedDict(
        [
            ("name", process_name),
            (
                "class",
                _safe_field(
                    class_name, "classdef line not found" if class_name is None else None
                ),
            ),
            (
                "matlab_source",
                str(
                    Path(
                        "data/m1_sources/WholeCell/src/+edu/+stanford/+covert/+cell/+sim/+process"
                    )
                    / f"{process_name}.m"
                ).replace("\\", "/"),
            ),
            (
                "trace_file",
                str(
                    Path("data/m1_sources/karr_native/per_process_traces_v2")
                    / f"{process_name}_100ticks.mat"
                ).replace("\\", "/"),
            ),
            (
                "fixture_file",
                (
                    str(
                        Path("data/m1_sources/karr_native/per_process_fixtures_v2")
                        / f"{process_name}_fixture.mat"
                    ).replace("\\", "/")
                    if fixture_file.exists()
                    else "MISSING"
                ),
            ),
        ]
    )
    schema["substrates"] = OrderedDict(
        wids=_safe_field(substrate_wids, substrate_reason if substrate_wids is None else None),
        count=substrate_count_field,
        shape=substrate_shape if substrate_shape is not None else {"EXTRACTOR_FAILED": "substrates observable missing"},
        compartments=compartments,
        compartment_wids=compartment_wids,
        extractor_method=compartments_method,
        extractor_notes=(compartments_notes + (f"; {compartment_wids_notes}" if compartment_wids_notes else "")).strip("; "),
    )
    schema["enzymes"] = OrderedDict(
        free=OrderedDict(
            wids=_safe_field(enzyme_wids, enzyme_reason if enzyme_wids is None else None),
            count=enzyme_count_field,
            shape=enzymes_shape if enzymes_shape is not None else {"EXTRACTOR_FAILED": "enzymes observable missing"},
        ),
        bound=OrderedDict(
            wids=bound_wids_field,
            count=(
                len(enzyme_wids)
                if enzyme_wids is not None
                else (
                    _infer_item_count_from_shape(bound_shape)
                )
            ),
            shape=bound_shape if bound_shape is not None else {"EXTRACTOR_FAILED": "boundEnzymes observable missing"},
        ),
    )
    schema["mutation_profile"] = mutation_profile
    schema["trace_hint_keys"] = _derive_trace_hint_keys(mutated)
    schema["pass_through"] = _derive_pass_through(mutated)

    # Additional extractor diagnostics aid manual audits and downstream tooling.
    schema["extractor_diagnostics"] = OrderedDict(
        source_lines=OrderedDict(
            classdef_line=_line_number(process_text, r"classdef\s+") or -1,
            substrate_ids_line=_line_number(process_text, r"substrateWholeCellModelIDs") or -1,
            enzyme_ids_line=_line_number(process_text, r"enzymeWholeCellModelIDs") or -1,
            substrate_compartments_line=_line_number(process_text, r"substrateCompartments")
            or -1,
        ),
        axis_inference=OrderedDict(
            substrate_axis=substrate_axis,
            compartment_axis=compartment_axis,
            axis_method=axis_method,
            class_base=class_base if class_base is not None else "UNKNOWN",
            local_compartment_indexs=(
                OrderedDict(
                    sorted(
                        (
                            name,
                            idx,
                        )
                        for name, idx in local_compartment_named.items()
                    )
                )
                if local_compartment_named
                else {"EXTRACTOR_FAILED": local_compartment_reason}
            ),
        ),
    )
    return schema


def _toml_escape_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _toml_scalar(value: Any) -> str:
    if isinstance(value, str):
        return f'"{_toml_escape_string(value)}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if np.isnan(value):
            return "nan"
        if np.isposinf(value):
            return "inf"
        if np.isneginf(value):
            return "-inf"
        return repr(value)
    raise TypeError(f"Unsupported scalar type: {type(value)!r}")


def _toml_value(value: Any) -> str:
    if isinstance(value, (str, bool, int, float)):
        return _toml_scalar(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(v) for v in value) + "]"
    if isinstance(value, dict):
        items = ", ".join(f"{k} = {_toml_value(v)}" for k, v in value.items())
        return "{ " + items + " }"
    raise TypeError(f"Unsupported TOML value: {type(value)!r}")


def _emit_table(lines: list[str], table_name: str, table: dict[str, Any]) -> None:
    lines.append(f"[{table_name}]")
    for key, value in table.items():
        if isinstance(value, dict) and value and all(
            not isinstance(v, (dict, list)) for v in value.values()
        ):
            lines.append(f"{key} = {_toml_value(value)}")
        elif isinstance(value, dict) and value and "EXTRACTOR_FAILED" in value and len(value) == 1:
            lines.append(f"{key} = {_toml_value(value)}")
        else:
            lines.append(f"{key} = {_toml_value(value)}")
    lines.append("")


def render_schema_toml(schema: dict[str, Any]) -> str:
    lines: list[str] = [AUTOGEN_HEADER.rstrip("\n"), ""]
    _emit_table(lines, "process", schema["process"])
    _emit_table(lines, "substrates", schema["substrates"])
    _emit_table(lines, "enzymes.free", schema["enzymes"]["free"])
    _emit_table(lines, "enzymes.bound", schema["enzymes"]["bound"])
    _emit_table(lines, "mutation_profile", {
        "bound_mutated_ticks": schema["mutation_profile"]["bound_mutated_ticks"],
        "enzymes_mutated_ticks": schema["mutation_profile"]["enzymes_mutated_ticks"],
        "substrates_mutated_ticks": schema["mutation_profile"]["substrates_mutated_ticks"],
        "monomers_mutated_ticks": schema["mutation_profile"]["monomers_mutated_ticks"],
        "per_observable": schema["mutation_profile"]["per_observable"],
    })
    lines.append(f"trace_hint_keys = {_toml_value(schema['trace_hint_keys'])}")
    lines.append(f"pass_through = {_toml_value(schema['pass_through'])}")
    lines.append("")
    _emit_table(lines, "extractor_diagnostics.source_lines", schema["extractor_diagnostics"]["source_lines"])
    _emit_table(lines, "extractor_diagnostics.axis_inference", schema["extractor_diagnostics"]["axis_inference"])
    return "\n".join(lines).rstrip() + "\n"


def list_process_names(trace_dir: Path) -> list[str]:
    names = []
    for p in sorted(trace_dir.glob("*_100ticks.mat")):
        names.append(p.name.replace("_100ticks.mat", ""))
    return names


def write_schema_file(process_name: str, schema: dict[str, Any], output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    snake = camel_to_snake(process_name)
    out_path = output_dir / f"{snake}.toml"
    out_path.write_text(render_schema_toml(schema), encoding="utf-8")
    return out_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--process",
        action="append",
        default=[],
        help="Process name (CamelCase). Repeat for multiple.",
    )
    parser.add_argument(
        "--wholecell-root",
        default=None,
        help="Optional explicit WholeCell root containing src/",
    )
    parser.add_argument(
        "--output-dir",
        default=str(OUTPUT_DIR_REL),
        help="Output directory for generated TOML files.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print targets without writing files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    paths = build_paths(args.wholecell_root)
    requested = args.process or list_process_names(paths.trace_dir)
    output_dir = (
        Path(args.output_dir)
        if Path(args.output_dir).is_absolute()
        else paths.repo_root / args.output_dir
    )
    written = 0
    for name in requested:
        schema = extract_process_schema(name, paths)
        if args.dry_run:
            print(f"[dry-run] would write: {output_dir / (camel_to_snake(name) + '.toml')}")
            continue
        out = write_schema_file(name, schema, output_dir)
        written += 1
        print(f"[ok] {name} -> {out}")
    if not args.dry_run:
        print(f"wrote {written}/{len(requested)} schema files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
