#!/usr/bin/env python3
"""Extract per-process schema TOMLs using fixture-first v2.1 rules."""

from __future__ import annotations

import argparse
import ast
import dataclasses
import importlib
import re
from collections import OrderedDict
from functools import lru_cache
from pathlib import Path
from typing import Any

import h5py
import numpy as np
from scipy.io import loadmat


PROCESS_M_REL = Path(
    "data/m1_sources/WholeCell/src/+edu/+stanford/+covert/+cell/+sim/+process"
)
TRACE_DIR_REL = Path("data/m1_sources/karr_native/per_process_traces_v2")
TRACE_S000_DIR_REL = Path("data/m1_sources/karr_native/per_process_traces_v2_s000")
FIXTURE_DIR_REL = Path("data/karr_fixtures/per_process")
OUTPUT_DIR_REL = Path("data/schemas/per_process")
TESTS_DIR_REL = Path("tests/vivarium")
VIVARIUM_DIR_REL = Path("opencell/vivarium")

AUTOGEN_HEADER = (
    "# AUTOGENERATED by scripts/extract_per_process_schema_v2.py — DO NOT EDIT\n"
)

SCHEMA_VERSION = "2.1"
CANONICAL_POOLS = ("substrates", "enzymes", "monomers", "complexs", "rnas")
CHROMOSOME_FIELDS = (
    "polymerizedRegions",
    "linkingNumbers",
    "monomerBoundSites",
    "complexBoundSites",
    "gapSites",
    "abasicSites",
    "damagedSugarPhosphates",
    "damagedBases",
    "intrastrandCrossLinks",
    "strandBreaks",
    "hollidayJunctions",
)
CHROMOSOME_PROCESS_NAMES = {
    "DNASupercoiling",
    "DNARepair",
    "DNADamage",
    "Replication",
    "ReplicationInitiation",
    "Cytokinesis",
}

POOL_ATTR_CANDIDATES: dict[str, tuple[str, ...]] = {
    "substrates": (
        "substrate_wids",
        "allocation_substrate_wids",
        "request_wids",
        "vector_wids",
    ),
    "enzymes": ("enzyme_wids",),
    "monomers": (
        "monomer_wids",
        "protein_wids",
        "protein_ids",
        "processed_monomer_wids",
        "unprocessed_monomer_wids",
        "folded_monomer_wids",
        "unfolded_monomer_wids",
        "modified_monomer_wids",
        "unmodified_monomer_wids",
        "signal_sequence_monomer_wids",
    ),
    "complexs": ("complex_wids", "folded_complex_wids", "unfolded_complex_wids"),
    "rnas": (
        "rna_wids",
        "free_rna_wids",
        "aminoacylated_rna_wids",
        "processed_rna_wids",
        "unprocessed_rna_wids",
        "modified_rna_wids",
        "unmodified_rna_wids",
        "intergenic_rna_wids",
        "free_trna_wids",
        "aminoacylated_trna_wids",
    ),
}


@dataclasses.dataclass(frozen=True)
class Paths:
    repo_root: Path
    process_dir: Path
    trace_dir: Path
    trace_s000_dir: Path
    fixture_dir: Path
    tests_dir: Path
    vivarium_dir: Path


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _existing_path(candidates: list[Path], label: str) -> Path:
    for candidate in candidates:
        if candidate.exists():
            return candidate
    tried = "\n".join(str(c) for c in candidates)
    raise FileNotFoundError(f"Unable to resolve {label}. Tried:\n{tried}")


def build_paths() -> Paths:
    repo_root = _repo_root()
    return Paths(
        repo_root=repo_root,
        process_dir=_existing_path(
            [repo_root / PROCESS_M_REL, Path("E:/opencell") / PROCESS_M_REL],
            "MATLAB process source directory",
        ),
        trace_dir=_existing_path(
            [repo_root / TRACE_DIR_REL, Path("E:/opencell") / TRACE_DIR_REL],
            "v2 trace directory",
        ),
        trace_s000_dir=_existing_path(
            [repo_root / TRACE_S000_DIR_REL, Path("E:/opencell") / TRACE_S000_DIR_REL],
            "v2_s000 trace directory",
        ),
        fixture_dir=_existing_path(
            [repo_root / FIXTURE_DIR_REL, Path("E:/opencell") / FIXTURE_DIR_REL],
            "fixture directory",
        ),
        tests_dir=_existing_path(
            [repo_root / TESTS_DIR_REL, Path("E:/opencell") / TESTS_DIR_REL],
            "tests/vivarium directory",
        ),
        vivarium_dir=_existing_path(
            [repo_root / VIVARIUM_DIR_REL, Path("E:/opencell") / VIVARIUM_DIR_REL],
            "opencell/vivarium directory",
        ),
    )


def camel_to_snake(name: str) -> str:
    name = name.replace("tRNA", "TRNA")
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1)
    return s2.lower()


def _snake_to_process_name(snake_name: str) -> str:
    overrides = {
        "trna_aminoacylation": "tRNAAminoacylation",
        "fts_z_polymerization": "FtsZPolymerization",
        "dna_damage": "DNADamage",
        "dna_repair": "DNARepair",
        "dna_supercoiling": "DNASupercoiling",
        "rna_decay": "RNADecay",
        "rna_modification": "RNAModification",
        "rna_processing": "RNAProcessing",
    }
    if snake_name in overrides:
        return overrides[snake_name]
    return "".join(part.capitalize() for part in snake_name.split("_"))


def _to_str_list(raw: Any) -> list[str]:
    try:
        values = list(raw.ravel())  # numpy arrays
    except Exception:
        values = [raw]
    out: list[str] = []
    for item in values:
        obj = item
        while hasattr(obj, "shape") and getattr(obj, "shape", None) and getattr(obj, "size", 1) == 1:
            try:
                obj = obj.item()
            except Exception:
                break
        if isinstance(obj, bytes):
            text = obj.decode("utf-8", errors="replace").strip()
        else:
            text = str(obj).strip()
        if text:
            out.append(text)
    return out


def _dedupe_keep_order(values: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        out.append(value)
    return out


def _attr_to_pool(attr_name: str) -> str | None:
    lower = attr_name.lower()
    if "wholecellmodelid" not in lower:
        return None
    if "reaction" in lower or "stimuli" in lower or "stimulus" in lower:
        return None
    if "processwholecellmodelids" in lower:
        return None
    if "compartmentwholecellmodelids" in lower:
        return None
    if "transcriptionunitwholecellmodelids" in lower:
        return None
    if "substrate" in lower:
        return "substrates"
    if "enzyme" in lower:
        return "enzymes"
    if "monomer" in lower:
        return "monomers"
    if "complex" in lower:
        return "complexs"
    if "rna" in lower:
        return "rnas"
    return None


def _line_number(text: str, pattern: str) -> int:
    match = re.search(pattern, text, re.S)
    if not match:
        return -1
    return text[: match.start()].count("\n") + 1


def _tick_refs(dataset: h5py.Dataset) -> list[h5py.Reference]:
    if dataset.ndim != 2:
        return [dataset[idx] for idx in np.ndindex(dataset.shape)]
    if dataset.shape[0] == 1:
        return [dataset[0, i] for i in range(dataset.shape[1])]
    if dataset.shape[1] == 1:
        return [dataset[i, 0] for i in range(dataset.shape[0])]
    return [dataset[idx] for idx in np.ndindex(dataset.shape)]


def _load_tick_matrices(handle: h5py.File, group_name: str, observable: str) -> list[np.ndarray]:
    dataset = handle[f"{group_name}/{observable}"]
    refs = _tick_refs(dataset)
    out: list[np.ndarray] = []
    for ref in refs:
        out.append(np.asarray(handle[ref][()]))
    return out


def _observable_to_pool(observable_name: str) -> str:
    lower = observable_name.lower()
    if "substrate" in lower:
        return "substrates"
    if "enzyme" in lower:
        return "enzymes"
    if "complex" in lower:
        return "complexs"
    if "rna" in lower:
        return "rnas"
    if "monomer" in lower:
        return "monomers"
    raise ValueError(f"Unable to map observable to pool: {observable_name}")


def extract_trace_observables(
    trace_file: Path,
) -> tuple[OrderedDict[str, dict[str, Any]], OrderedDict[str, int], list[str], list[str]]:
    observables: OrderedDict[str, dict[str, Any]] = OrderedDict()
    mutation_counts: OrderedDict[str, int] = OrderedDict()

    with h5py.File(trace_file, "r") as handle:
        before_keys = set(handle["states_before"].keys())
        after_keys = set(handle["states_after"].keys())
        for observable in sorted(before_keys | after_keys):
            if observable == "chromosome":
                continue
            if f"states_before/{observable}" not in handle or f"states_after/{observable}" not in handle:
                continue
            before = _load_tick_matrices(handle, "states_before", observable)
            after = _load_tick_matrices(handle, "states_after", observable)
            count = 0
            for idx in range(min(len(before), len(after))):
                if not np.array_equal(before[idx], after[idx]):
                    count += 1
            mutation_counts[observable] = int(count)
            shape = [int(dim) for dim in before[0].shape] if before else []
            observables[observable] = {
                "pool": _observable_to_pool(observable),
                "shape": shape,
            }

    trace_hint_keys: list[str] = []
    for observable in ("boundEnzymes", "enzymes"):
        if mutation_counts.get(observable, 0) > 0:
            trace_hint_keys.append(f"{observable}_next")
    pass_through = sorted([name for name, count in mutation_counts.items() if count == 0])
    return observables, mutation_counts, trace_hint_keys, pass_through


def resolve_trace_file(process_name: str, paths: Paths) -> tuple[Path, str]:
    s000 = paths.trace_s000_dir / f"{process_name}_100ticks.mat"
    if s000.exists():
        return s000, "per_process_traces_v2_s000"
    fallback = paths.trace_dir / f"{process_name}_100ticks.mat"
    if fallback.exists():
        return fallback, "per_process_traces_v2"
    raise FileNotFoundError(f"Trace file missing for {process_name}")


def resolve_fixture_file(process_name: str, paths: Paths) -> Path:
    fixture_file = paths.fixture_dir / f"{process_name}_flat.mat"
    if fixture_file.exists():
        return fixture_file
    raise FileNotFoundError(f"Fixture file missing for {process_name}: {fixture_file}")


def list_process_names(paths: Paths) -> list[str]:
    names: list[str] = []
    for path in sorted(paths.process_dir.glob("*.m")):
        names.append(path.stem)
    return names


def extract_species_pools_from_fixture(fixture_file: Path) -> tuple[dict[str, list[str]], dict[str, int]]:
    mat = loadmat(str(fixture_file), squeeze_me=True, struct_as_record=False)
    data = mat.get("data")
    if data is None or not hasattr(data, "fixture"):
        raise ValueError("Fixture MAT missing data.fixture root")
    fixture = data.fixture

    pooled: dict[str, list[str]] = {pool: [] for pool in CANONICAL_POOLS}
    source_attrs = 0
    for attr_name in dir(fixture):
        pool = _attr_to_pool(attr_name)
        if pool is None:
            continue
        source_attrs += 1
        pooled[pool].extend(_to_str_list(getattr(fixture, attr_name)))
    deduped = {pool: _dedupe_keep_order(values) for pool, values in pooled.items()}
    counts = {pool: len(values) for pool, values in deduped.items()}
    counts["source_attrs"] = source_attrs
    return deduped, counts


def _strip_matlab_comments(text: str) -> str:
    out: list[str] = []
    for line in text.splitlines():
        idx = line.find("%")
        if idx >= 0:
            line = line[:idx]
        out.append(line)
    return "\n".join(out)


def extract_matlab_chromosome_fields(process_text: str) -> tuple[list[str], list[str]]:
    code = _strip_matlab_comments(process_text)
    aliases = {"chromosome"}
    for match in re.finditer(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?:this\.)?chromosome\s*;", code):
        aliases.add(match.group(1))
    reads: set[str] = set()
    writes: set[str] = set()
    for line in code.splitlines():
        if all(f"{alias}." not in line for alias in aliases):
            continue
        for field in CHROMOSOME_FIELDS:
            alias_expr = "|".join(re.escape(alias) for alias in sorted(aliases))
            field_pat = rf"(?:(?:this\.)?chromosome|(?:{alias_expr}))\.{re.escape(field)}\b"
            occurrences = len(re.findall(field_pat, line))
            if occurrences == 0:
                continue
            write_occurrences = len(
                re.findall(rf"{field_pat}[^=;\n]*=(?!=)", line)
            )
            if write_occurrences > 0:
                writes.add(field)
            if occurrences > write_occurrences or write_occurrences == 0:
                reads.add(field)
    ordered_reads = [field for field in CHROMOSOME_FIELDS if field in reads]
    ordered_writes = [field for field in CHROMOSOME_FIELDS if field in writes]
    return ordered_reads, ordered_writes


class _OCChromosomeFieldVisitor(ast.NodeVisitor):
    def __init__(self) -> None:
        super().__init__()
        self.symbol_map: dict[str, tuple[str, ...]] = {}
        self.loop_bindings: list[dict[str, tuple[str, ...]]] = []
        self.function_stack: list[str] = []
        self.reads: set[str] = set()
        self.writes: set[str] = set()

    def _in_runtime_context(self) -> bool:
        if not self.function_stack:
            return False
        name = self.function_stack[-1]
        return name == "next_update" or "chromosome" in name.lower()

    def _resolve_name(self, name: str) -> tuple[str, ...]:
        for mapping in reversed(self.loop_bindings):
            if name in mapping:
                return mapping[name]
        return self.symbol_map.get(name, ())

    def _resolve_field_values(self, node: ast.AST | None) -> tuple[str, ...]:
        if node is None:
            return ()
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            if node.value in CHROMOSOME_FIELDS:
                return (node.value,)
            return ()
        if isinstance(node, ast.Name):
            return self._resolve_name(node.id)
        if isinstance(node, (ast.Tuple, ast.List, ast.Set)):
            out: list[str] = []
            for elt in node.elts:
                out.extend(self._resolve_field_values(elt))
            deduped = []
            seen: set[str] = set()
            for value in out:
                if value not in seen:
                    seen.add(value)
                    deduped.append(value)
            return tuple(deduped)
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            if node.func.id == "set" and node.args:
                return self._resolve_field_values(node.args[0])
        return ()

    def _slice_node(self, node: ast.Subscript) -> ast.AST | None:
        slice_node = node.slice
        if isinstance(slice_node, ast.Index):  # pragma: no cover (py<3.9 compatibility)
            return slice_node.value
        return slice_node

    def _subscript_fields(self, node: ast.Subscript) -> tuple[str, ...]:
        return self._resolve_field_values(self._slice_node(node))

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self.function_stack.append(node.name)
        self.generic_visit(node)
        self.function_stack.pop()

    def visit_Assign(self, node: ast.Assign) -> None:
        if len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            values = self._resolve_field_values(node.value)
            if values:
                self.symbol_map[node.targets[0].id] = values
        if self._in_runtime_context():
            for target in node.targets:
                if isinstance(target, ast.Subscript):
                    self.writes.update(self._subscript_fields(target))
        self.generic_visit(node)

    def visit_AnnAssign(self, node: ast.AnnAssign) -> None:
        if self._in_runtime_context() and isinstance(node.target, ast.Subscript):
            self.writes.update(self._subscript_fields(node.target))
        self.generic_visit(node)

    def visit_For(self, node: ast.For) -> None:
        if isinstance(node.target, ast.Name):
            values = self._resolve_field_values(node.iter)
            if values:
                self.loop_bindings.append({node.target.id: values})
                for statement in node.body:
                    self.visit(statement)
                self.loop_bindings.pop()
                for statement in node.orelse:
                    self.visit(statement)
                return
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        if self._in_runtime_context() and isinstance(node.func, ast.Attribute):
            method_name = node.func.attr
            if node.args:
                fields = self._resolve_field_values(node.args[0])
            else:
                fields = ()
            if method_name == "get_field":
                self.reads.update(fields)
            elif method_name == "set_field":
                self.writes.update(fields)
        self.generic_visit(node)


def extract_oc_chromosome_fields(oc_source_text: str) -> tuple[list[str], list[str]]:
    tree = ast.parse(oc_source_text)
    visitor = _OCChromosomeFieldVisitor()
    visitor.visit(tree)
    reads = [field for field in CHROMOSOME_FIELDS if field in visitor.reads]
    writes = [field for field in CHROMOSOME_FIELDS if field in visitor.writes]
    return reads, writes


@lru_cache(maxsize=1)
def load_process_test_import_map(tests_dir: Path) -> dict[str, tuple[str, str]]:
    mapping: dict[str, tuple[str, str]] = {}
    for test_file in sorted(tests_dir.glob("test_karr_*_l2_replay.py")):
        snake_name = test_file.stem[len("test_karr_") : -len("_l2_replay")]
        text = test_file.read_text(encoding="utf-8", errors="replace")
        match = re.search(
            r"from\s+opencell\.vivarium\.(?P<module>[A-Za-z0-9_]+)\s+import\s+(?P<class>[A-Za-z0-9_]+)",
            text,
        )
        if match:
            mapping[snake_name] = (match.group("module"), match.group("class"))
    return mapping


def _snake_aliases(snake_name: str) -> tuple[str, ...]:
    aliases = [snake_name]
    aliases.append(snake_name.replace("fts_z_", "ftsz_"))
    if snake_name == "trna_aminoacylation":
        aliases.append("trna_aminoacylation")
    return tuple(dict.fromkeys(aliases))


def _normalize_attr_values(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, (str, bytes)):
        return _to_str_list(np.asarray([value], dtype=object))
    if isinstance(value, np.ndarray):
        return _to_str_list(value)
    if isinstance(value, (list, tuple, set)):
        return _to_str_list(np.asarray(list(value), dtype=object))
    return []


def collect_oc_pool_wids(process_obj: Any) -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for pool_name, attrs in POOL_ATTR_CANDIDATES.items():
        values: list[str] = []
        for attr_name in attrs:
            if not hasattr(process_obj, attr_name):
                continue
            values.extend(_normalize_attr_values(getattr(process_obj, attr_name)))
        out[pool_name] = _dedupe_keep_order(values)
    return out


def build_pool_cross_check(
    fixture_pools: dict[str, list[str]], oc_pools: dict[str, list[str]]
) -> OrderedDict[str, dict[str, Any]]:
    out: OrderedDict[str, dict[str, Any]] = OrderedDict()
    for pool_name in CANONICAL_POOLS:
        fixture_wids = list(fixture_pools.get(pool_name, []))
        oc_wids = list(oc_pools.get(pool_name, []))
        fixture_set = set(fixture_wids)
        oc_set = set(oc_wids)
        only_fixture = sorted(fixture_set - oc_set)
        only_oc = sorted(oc_set - fixture_set)
        if not fixture_wids and not oc_wids:
            status = "both_empty"
        elif fixture_wids == oc_wids:
            status = "match"
        elif not only_fixture and not only_oc:
            status = "match_set_order_diff"
        elif not oc_wids:
            status = "oc_missing"
        elif not fixture_wids:
            status = "fixture_missing"
        else:
            status = "diverged"
        out[pool_name] = {
            "status": status,
            "fixture_count": len(fixture_wids),
            "oc_count": len(oc_wids),
            "only_in_fixture": only_fixture[:50],
            "only_in_oc": only_oc[:50],
            "only_in_fixture_truncated": max(0, len(only_fixture) - 50),
            "only_in_oc_truncated": max(0, len(only_oc) - 50),
        }
    return out


def extract_process_schema(process_name: str, paths: Paths) -> dict[str, Any]:
    matlab_source = paths.process_dir / f"{process_name}.m"
    if not matlab_source.exists():
        raise FileNotFoundError(f"MATLAB source missing for {process_name}")
    trace_file, trace_source = resolve_trace_file(process_name, paths)
    fixture_file = resolve_fixture_file(process_name, paths)

    process_text = matlab_source.read_text(encoding="utf-8", errors="replace")
    species_pools, pool_counts = extract_species_pools_from_fixture(fixture_file)
    observables, mutation_counts, trace_hint_keys, pass_through = extract_trace_observables(
        trace_file
    )
    snake_name = camel_to_snake(process_name)
    test_import_map = load_process_test_import_map(paths.tests_dir)

    oc_module_name: str | None = None
    oc_class_name: str | None = None
    oc_source_rel: str | None = None
    cross_check: OrderedDict[str, dict[str, Any]] | dict[str, Any]
    cross_check_error = ""
    oc_pools: dict[str, list[str]] = {pool: [] for pool in CANONICAL_POOLS}

    module_tuple = None
    for alias in _snake_aliases(snake_name):
        if alias in test_import_map:
            module_tuple = test_import_map[alias]
            break
    if module_tuple is None:
        cross_check = {"status": "missing_test_import_mapping"}
        cross_check_error = "No test import mapping found"
    else:
        oc_module_name, oc_class_name = module_tuple
        oc_source_path = paths.vivarium_dir / f"{oc_module_name}.py"
        if oc_source_path.exists():
            oc_source_rel = str(oc_source_path.relative_to(paths.repo_root)).replace("\\", "/")
        try:
            module = importlib.import_module(f"opencell.vivarium.{oc_module_name}")
            cls = getattr(module, oc_class_name)
            process_obj = cls({})
            oc_pools = collect_oc_pool_wids(process_obj)
            cross_check = build_pool_cross_check(species_pools, oc_pools)
        except Exception as exc:  # noqa: BLE001
            cross_check = {"status": "oc_instantiation_failed"}
            cross_check_error = f"{type(exc).__name__}: {exc}"

    chromosome_table: OrderedDict[str, Any] | None = None
    if process_name in CHROMOSOME_PROCESS_NAMES:
        matlab_reads, matlab_writes = extract_matlab_chromosome_fields(process_text)
        oc_reads: list[str] = []
        oc_writes: list[str] = []
        if oc_module_name is not None:
            oc_source_path = paths.vivarium_dir / f"{oc_module_name}.py"
            if oc_source_path.exists():
                oc_text = oc_source_path.read_text(encoding="utf-8", errors="replace")
                oc_reads, oc_writes = extract_oc_chromosome_fields(oc_text)
        fields_read = [f for f in CHROMOSOME_FIELDS if f in set(matlab_reads) | set(oc_reads)]
        fields_written = [
            f for f in CHROMOSOME_FIELDS if f in set(matlab_writes) | set(oc_writes)
        ]
        divergence = OrderedDict(
            [
                (
                    "matlab_only_read",
                    [f for f in CHROMOSOME_FIELDS if f in set(matlab_reads) - set(oc_reads)],
                ),
                (
                    "oc_only_read",
                    [f for f in CHROMOSOME_FIELDS if f in set(oc_reads) - set(matlab_reads)],
                ),
                (
                    "matlab_only_written",
                    [f for f in CHROMOSOME_FIELDS if f in set(matlab_writes) - set(oc_writes)],
                ),
                (
                    "oc_only_written",
                    [f for f in CHROMOSOME_FIELDS if f in set(oc_writes) - set(matlab_writes)],
                ),
            ]
        )
        if not any(divergence.values()):
            divergence = OrderedDict()
        chromosome_table = OrderedDict(
            [
                ("fields_read", fields_read),
                ("fields_written", fields_written),
                ("matlab_fields_read", matlab_reads),
                ("oc_fields_read", oc_reads),
                ("matlab_fields_written", matlab_writes),
                ("oc_fields_written", oc_writes),
                ("divergence", divergence),
            ]
        )

    schema: dict[str, Any] = OrderedDict()
    schema["process"] = OrderedDict(
        [
            ("name", process_name),
            ("class", process_name),
            ("schema_version", SCHEMA_VERSION),
            (
                "matlab_source",
                str(
                    Path(
                        "data/m1_sources/WholeCell/src/+edu/+stanford/+covert/+cell/+sim/+process"
                    )
                    / f"{process_name}.m"
                ).replace("\\", "/"),
            ),
            (
                "trace_file",
                str(trace_file.relative_to(paths.repo_root)).replace("\\", "/"),
            ),
            (
                "fixture_file",
                str(fixture_file.relative_to(paths.repo_root)).replace("\\", "/"),
            ),
        ]
    )
    schema["species_pools"] = OrderedDict((pool, species_pools[pool]) for pool in CANONICAL_POOLS)
    schema["observables"] = OrderedDict((name, observables[name]) for name in observables)
    if chromosome_table is not None:
        schema["chromosome"] = chromosome_table
    schema["activity_profile"] = OrderedDict(
        [
            ("bound_mutated_ticks", int(mutation_counts.get("boundEnzymes", 0))),
            ("enzymes_mutated_ticks", int(mutation_counts.get("enzymes", 0))),
            ("substrates_mutated_ticks", int(mutation_counts.get("substrates", 0))),
            ("monomers_mutated_ticks", int(mutation_counts.get("monomers", 0))),
            ("per_observable", OrderedDict((k, int(v)) for k, v in mutation_counts.items())),
            ("trace_hint_keys", trace_hint_keys),
            ("pass_through", pass_through),
        ]
    )
    schema["extractor_diagnostics"] = OrderedDict(
        [
            (
                "source_lines",
                OrderedDict(
                    [
                        ("classdef_line", _line_number(process_text, r"classdef\s+")),
                        (
                            "substrate_ids_line",
                            _line_number(process_text, r"substrateWholeCellModelIDs"),
                        ),
                        (
                            "enzyme_ids_line",
                            _line_number(process_text, r"enzymeWholeCellModelIDs"),
                        ),
                    ]
                ),
            ),
            (
                "provenance",
                OrderedDict(
                    [
                        ("wids_source", "fixture"),
                        ("observable_source", "trace_states_before"),
                        ("trace_source", trace_source),
                        ("fixture_loader", "scipy.io.loadmat"),
                        ("oc_runtime_source", "tests_l2_replay_import_map"),
                    ]
                ),
            ),
            ("species_pool_counts", pool_counts),
            ("cross_check", cross_check),
        ]
    )
    if oc_module_name is not None:
        schema["extractor_diagnostics"]["provenance"]["oc_module"] = oc_module_name
    if oc_class_name is not None:
        schema["extractor_diagnostics"]["provenance"]["oc_class"] = oc_class_name
    if oc_source_rel is not None:
        schema["extractor_diagnostics"]["provenance"]["oc_source"] = oc_source_rel
    if cross_check_error:
        schema["extractor_diagnostics"]["provenance"]["cross_check_error"] = cross_check_error
    return schema


def _toml_escape_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _toml_scalar(value: Any) -> str:
    if isinstance(value, str):
        return f'"{_toml_escape_string(value)}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    raise TypeError(f"Unsupported scalar type: {type(value)!r}")


def _toml_value(value: Any) -> str:
    if isinstance(value, (str, bool, int)):
        return _toml_scalar(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    if isinstance(value, dict):
        items = ", ".join(f"{key} = {_toml_value(val)}" for key, val in value.items())
        return "{ " + items + " }"
    raise TypeError(f"Unsupported TOML type: {type(value)!r}")


def _emit_table(lines: list[str], table_name: str, table: dict[str, Any]) -> None:
    lines.append(f"[{table_name}]")
    for key, value in table.items():
        lines.append(f"{key} = {_toml_value(value)}")
    lines.append("")


def render_schema_toml(schema: dict[str, Any]) -> str:
    lines = [AUTOGEN_HEADER.rstrip("\n"), ""]
    _emit_table(lines, "process", schema["process"])
    _emit_table(lines, "species_pools", schema["species_pools"])
    for observable_name, table in schema["observables"].items():
        _emit_table(lines, f"observables.{observable_name}", table)
    if "chromosome" in schema:
        _emit_table(lines, "chromosome", schema["chromosome"])
    _emit_table(lines, "activity_profile", schema["activity_profile"])
    _emit_table(lines, "extractor_diagnostics.source_lines", schema["extractor_diagnostics"]["source_lines"])
    _emit_table(lines, "extractor_diagnostics.provenance", schema["extractor_diagnostics"]["provenance"])
    _emit_table(
        lines,
        "extractor_diagnostics.species_pool_counts",
        schema["extractor_diagnostics"]["species_pool_counts"],
    )
    _emit_table(
        lines,
        "extractor_diagnostics.cross_check",
        schema["extractor_diagnostics"]["cross_check"],
    )
    return "\n".join(lines).rstrip() + "\n"


def write_schema_file(process_name: str, schema: dict[str, Any], output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{camel_to_snake(process_name)}.toml"
    out_path.write_text(render_schema_toml(schema), encoding="utf-8")
    return out_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--process",
        action="append",
        default=[],
        help="Process name in CamelCase. Repeat for multiple.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(OUTPUT_DIR_REL),
        help="Output directory for generated TOMLs.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Resolve and parse inputs without writing output files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    paths = build_paths()
    output_dir = (
        Path(args.output_dir)
        if Path(args.output_dir).is_absolute()
        else paths.repo_root / args.output_dir
    )

    requested = args.process
    if requested:
        process_names = []
        for process in requested:
            if "_" in process:
                process_names.append(_snake_to_process_name(process))
            else:
                process_names.append(process)
    else:
        process_names = list_process_names(paths)

    written = 0
    for process_name in process_names:
        schema = extract_process_schema(process_name, paths)
        if args.dry_run:
            print(f"[dry-run] {process_name}: fixture/species_pools parsed")
            continue
        out = write_schema_file(process_name, schema, output_dir)
        written += 1
        print(f"[ok] {process_name} -> {out}")

    if not args.dry_run:
        print(f"wrote {written}/{len(process_names)} schema files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
